#!/bin/sh
# javarifier: command-line interface for Javarifier that uses development
# version of Javarifier (rather than jarfiles in distribution).

# usage: javarifier <options-and-classes>

DIRNAME=$(dirname $0)

set -x
ant -f ${DIRNAME}/build.xml -e javarify \
         -Duser-soot-programs=${SOOT_PROGRAMS} \
         -Duser-soot-stubs=${SOOT_STUBS} \
         -Duser-soot-worlds=${SOOT_WORLD} \
         -Duser-args=\""$@\""
