#!/bin/sh
# javarify: command-line interface for Javarifier

# usage: javarifier [options] classes

# See javarifier.html for more information.

JDK=${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/jre/lib/resources.jar:${JAVA_HOME}/jre/lib/management-agent.jar:${JAVA_HOME}/jre/lib/jsse.jar:${JAVA_HOME}/jre/lib/jce.jar:${JAVA_HOME}/jre/lib/charsets.jar

DIRNAME=$(dirname $0)
SOOT_PROGRAMS=${CLASSPATH}
${JAVARIFIER_JDK:=${DIRNAME}/../annotated-jdk}

# If user provides -programCPEntries, their arguments will be passed in
# through the "$@" argument, and will override the CLASSPATH default.

JAVARIFIER_LIB=${DIRNAME}/../lib
JAVARIFIER_BIN=${DIRNAME}/../bin

java -Xmx400m -cp ${JAVARIFIER_BIN}:${JAVARIFIER_LIB}/javarifier.jar:${JAVARIFIER_LIB}/jasminclasses-2.2.3.jar:${JAVARIFIER_LIB}/polyglotclasses-1.3.2.jar:${JAVARIFIER_LIB}/sootclasses-2.2.3.jar:${CLASSPATH} \
	 javarifier.Main \
	 -defaultStubCPEntries ${JAVARIFIER_JDK} \
	 -defaultWorldCPEntries ${JDK} \
	 -programCPEntries ${SOOT_PROGRAMS} \
	 "$@"

# Remove temporaray soot output directory.
rm -rf ${DIRNAME}/sootOutput
