#!/bin/sh
# javarify: command-line interface for Javarifier

# usage: javarifier [options] classes

# See javarifier.html for more information.

DIRNAME=$(dirname $0)
SOOT_PROGRAMS=${CLASSPATH}
# If user provides -programCPEntries, their arguments will be passed in
# through the "$@" argument, and will override the CLASSPATH default.

JAVARIFIER_LIB=${DIRNAME}/lib

java -Xmx400m -cp ${JAVARIFIER_LIB}/javarifier.jar:${JAVARIFIER_LIB}/jasminclasses-2.2.3.jar:${JAVARIFIER_LIB}/polyglotclasses-1.3.2.jar:${JAVARIFIER_LIB}/sootclasses-2.2.3.jar:${CLASSPATH} \
	 javarifier.Main \
	 -defaultStubCPEntries ${DIRNAME}/annotated-jdk \
	 -defaultWorldCPEntries ${CLASSPATH} \
	 -programCPEntries ${SOOT_PROGRAMS} \
	 "$@"

# Remove temporaray soot output directory.
rm -rf ${DIRNAME}/sootOutput
